### ISSUE TITLE
Journeymap-overlayed Snitch fields are inaccurate

### ISSUE THREAD

**Issue by awoo-civ** [MrLittleKitty/Snitch-Master#8]
These snitches are placed so that their fields all touch each other:
![image](http://i.imgur.com/uw3ahMJ.png)
I'd expect the overlay to show that.

**Comment by MrLittleKitty** [comment]
Fixed it for the full screen overlay. However, at least in my journey map version, there is a rendering problem with the actual minimap that I can't fix.

Fix will be in the next update.

**Comment by Gjum** [comment]
Still too small on the minimap. Fullscreen map is ok now. Please reopen.

**Comment by awoo-civ** [comment]
He already said above that he can't fix it.

**Comment by Gjum** [comment]
Oh I missed that part, sorry. Still an issue though. I'll take a look myself later today.

**Comment by MrLittleKitty** [comment]
This bug is actually fixed in the latest JourneyMap version. (still 1.10.2) You can get it here: https://mods.curse.com/mc-mods/minecraft/journeymap-32274/2354561
